services:
  backend:
    build: ./crud-back
    container_name: crud-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/productsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build: ./crud-front
    container_name: crud-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: crud-db
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:


networks:
  mynetwork:
    driver: bridge
